spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    url: jdbc:p6spy:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level:
    root: warn
    com.yuki.dao: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.yuki.enums

